"""swarm.tools.path_guard -- path-protection and command-safety helpers."""

import re
from pathlib import Path

from swarm.tools import _shared
from swarm.tools._shared import _project_root


def _get_task_type() -> str:
    return _shared.TASK_TYPE

def _resolve_project_path(path_arg: str) -> Path:
    p = Path(path_arg)
    project_root = Path(_project_root())
    try:
        rel = p.relative_to(project_root)
        return project_root / rel
    except ValueError:
        return project_root / path_arg


def _is_vendor_path(path: Path) -> bool:
    return _protected_path_reason(path) == "vendor"


def _protected_path_reason(path: Path) -> str | None:
    try:
        rel = path.relative_to(Path(_project_root()))
    except ValueError:
        rel = path
    parts = rel.parts
    if not parts:
        return None
    if parts[0] == "addons":
        return "vendor"
    if parts[0] in {".godot", ".import"}:
        return "generated"
    if rel.suffix == ".uid":
        return "generated"
    return None


def _protected_path_error(path_arg: str, reason: str) -> dict:
    if reason == "vendor":
        detail = "Files under addons/ are third-party and read-only."
        label = "vendor code"
    else:
        detail = (
            "Files under .godot/, .import/, and *.uid are generated artifacts and "
            "must be regenerated by the engine instead of hand-edited."
        )
        label = "generated artifacts"
    return {
        "ok": False,
        "error": (
            f"Refusing to modify {label}: {path_arg}. "
            f"{detail}"
        ),
    }


def _command_targets_protected_path(cmd: str) -> tuple[str, str] | None:
    patterns = [
        ("vendor", r"(?<![\w./-])addons/"),
        ("generated", r"(?<![\w./-])\.godot/"),
        ("generated", r"(?<![\w./-])\.import/"),
        ("generated", r"(?<![\w./-])[^\\s'\"`|;&]+\.uid\b"),
    ]
    for reason, pattern in patterns:
        match = re.search(pattern, cmd)
        if match:
            return reason, match.group(0).strip()
    return None


def _embedded_protected_path_matches(cmd: str) -> list[tuple[str, str]]:
    patterns = [
        ("vendor", r"['\"](?P<path>addons/[^'\"]+)['\"]"),
        ("generated", r"['\"](?P<path>\.godot/[^'\"]+)['\"]"),
        ("generated", r"['\"](?P<path>\.import/[^'\"]+)['\"]"),
        ("generated", r"['\"](?P<path>[^'\"]+\.uid)['\"]"),
    ]
    matches: list[tuple[str, str]] = []
    for reason, pattern in patterns:
        for match in re.finditer(pattern, cmd):
            path_hint = (match.groupdict().get("path") or match.group(0)).strip("'\"")
            matches.append((reason, path_hint))
    return matches


def _command_attempts_embedded_protected_write(cmd: str) -> tuple[str, str] | None:
    lowered = cmd.lower()
    embedded_matches = _embedded_protected_path_matches(cmd)
    if not embedded_matches:
        return None

    python_write_patterns = [
        r"\bopen\s*\(\s*['\"][^'\"]+['\"]\s*,\s*['\"][waxt+]",
        r"\bpath\s*\(\s*['\"][^'\"]+['\"]\s*\)\.(?:write_text|write_bytes|touch|mkdir|rename|replace|unlink)\b",
        r"\bos\.(?:mkdir|makedirs|remove|unlink|rename|replace)\s*\(",
        r"\bshutil\.(?:copy|copy2|copyfile|move|rmtree)\s*\(",
    ]
    if any(re.search(pattern, lowered) for pattern in python_write_patterns):
        return embedded_matches[0]

    tee_match = re.search(r"\btee\b(?P<args>[^;&|]*)", cmd)
    if tee_match:
        tee_args = tee_match.group("args") or ""
        for reason, path_hint in embedded_matches:
            if path_hint in tee_args:
                return reason, path_hint

    return None


_CATASTROPHIC_PATTERNS: list[tuple[str, str]] = [
    # Recursive / force deletes -- rm -r, rm -rf, rm -fr, find ... -delete
    (r"\brm\s+(?:[^;|&\n]*\s)?-[a-z]*r[a-z]*f?[a-z]*\b", "recursive rm (-r/-rf/-fr)"),
    (r"\brm\s+(?:[^;|&\n]*\s)?-[a-z]*f[a-z]*r[a-z]*\b", "recursive rm (-fr/-rf)"),
    (r"\bfind\b[^;|&\n]*\s--delete\b", "find --delete (recursive file removal)"),
    (r"\bfind\b[^;|&\n]*\s-delete\b", "find -delete (recursive file removal)"),
    # Destructive git operations
    (r"\bgit\s+push\s+(?:[^;|&\n]*\s)?(?:--force|-f)\b", "git push --force"),
    (r"\bgit\s+push\s+(?:[^;|&\n]*\s)?--force-with-lease\b", "git push --force-with-lease"),
    (r"\bgit\s+reset\s+(?:[^;|&\n]*\s)?--hard\b", "git reset --hard"),
    (r"\bgit\s+branch\s+(?:[^;|&\n]*\s)?-D\b", "git branch -D (force branch delete)"),
    (r"\bgit\s+clean\s+(?:[^;|&\n]*\s)?-[a-z]*f[a-z]*\b", "git clean -f (destroys untracked files)"),
    (r"\bgit\s+filter-branch\b", "git filter-branch (rewrites history)"),
    (r"\bgit\s+filter-repo\b", "git filter-repo (rewrites history)"),
    # Process killing by name -- too broad / irreversible
    (r"\bpkill\b", "pkill (mass process kill by name)"),
    (r"\bkillall\b", "killall (mass process kill by name)"),
    # Disk-level writes
    (r"\bdd\s+if=", "dd if= (raw disk write)"),
    # Recursive permission/ownership bombs
    (r"\bchmod\s+(?:[^;|&\n]*\s)?-[a-z]*R[a-z]*\b", "chmod -R (recursive permission change)"),
    (r"\bchown\s+(?:[^;|&\n]*\s)?-[a-z]*R[a-z]*\b", "chown -R (recursive ownership change)"),
    # Truncating or overwriting the DB directly
    (r"swarm\.db", "direct access to swarm.db"),
    # Wiping the swarm data directory
    (r"\bdata/agent", "direct manipulation of swarm data/agent files via shell"),
]


def _check_catastrophic_command(cmd: str) -> str | None:
    """Return a human-readable reason if the command matches a catastrophic pattern, else None."""
    for pattern, reason in _CATASTROPHIC_PATTERNS:
        if re.search(pattern, cmd, re.IGNORECASE):
            return reason
    return None


def _command_attempts_protected_write(cmd: str) -> tuple[str, str] | None:
    if _get_task_type() == "project_create":
        return None

    target = _command_targets_protected_path(cmd)
    if not target:
        return None
    reason, path_hint = target
    lowered = cmd.lower()

    mutating_patterns = [
        r"\bcp\b",
        r"\bmv\b",
        r"\brm\b",
        r"\binstall\b",
        r"\bmkdir\b",
        r"\btouch\b",
        r"\bln\b",
        r"\brsync\b",
        r"\btee\b",
        r"\bsed\s+-i\b",
        r"\bperl\s+-i\b",
        r"\bgit\s+checkout\b",
        r"\bgit\s+restore\b",
        r"\bgit\s+clean\b",
    ]
    if any(re.search(pattern, lowered) for pattern in mutating_patterns):
        return reason, path_hint

    redirection_match = re.search(
        r"(?:^|[;&|])[^\\n]*?(?:>|>>)\s*(['\"]?)([^'\";&|]+)\1",
        cmd,
    )
    if redirection_match:
        redir_target = redirection_match.group(2).strip()
        if _command_targets_protected_path(redir_target):
            return reason, redir_target

    embedded_write = _command_attempts_embedded_protected_write(cmd)
    if embedded_write:
        return embedded_write

    return None


def _looks_like_dependency_path(value: str) -> bool:
    if not isinstance(value, str):
        return False
    text = value.strip()
    if not text:
        return False
    if "/" in text or "\\" in text:
        return True
    return text.lower().endswith((".gd", ".tscn", ".tres", ".py", ".json", ".md", ".png", ".wav"))
